-- Migration 038: Grant audit.view to admin role
--
-- Historical bug fix: admin was granted audit.export (migration 036) but not
-- audit.view; export is meant to be "more restrictive than view", so anyone who
-- can export must first be able to view. This migration originally granted
-- audit.view to the legacy 'admin' role.
--
-- The 'admin' role no longer exists in the modern schema — 000_squash.sql seeds
-- only the current role names, and migration 044 renamed the legacy roles
-- (admin→manager, manager→supervisor, staff→inventory_staff). Manager already
-- holds audit.view (and audit.export) from the 000_squash.sql seed, matching the
-- documented permission matrix (docs/audits/permission-matrix-final.md).
--
-- This file is therefore a NO-OP on a fresh deploy and is kept only to preserve
-- migration numbering/history. It deliberately contains no executable statements.

-- ROLLBACK:
-- DELETE FROM role_permissions
-- WHERE role_id = (SELECT id FROM roles WHERE name = 'admin')
--   AND permission_id = (SELECT id FROM permissions WHERE code = 'audit.view');